export const TOGGLE_CART = "TOGGLE_CART";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const UPDATE_INFO_FIELD = "UPDATE_INFO_FIELD";
export const SET_SUGGESTED_CITIES = "SET_SUGGESTED_CITIES";
